### ISSUE TITLE
first impressions

### ISSUE THREAD

**Issue by atomGit** [mattang687/mark-it#1]
i like the extension except for 2 items

* please consider not pulling fonts from google - this is a privacy issue and not necessary IMO
* needs a dark theme :)

i can do the latter if you're willing to do the former

**Comment by atomGit** [comment]
sorry, i decided to use [plibither8/markdown-new-tab](https://github.com/plibither8/markdown-new-tab) instead

**Comment by mattang687** [comment]
Hi,

First of all, thanks so much for trying this out and for taking the time to provide some feedback!

I agree that it was unnecessary to pull the fonts (Inconsolata and Quicksand) from Google, so I'm packaging them with the extension now (they're both under the Open Font License). I've also implemented the dark theme, as requested. I'm doing some testing now, but the update should be on the Firefox and Chrome stores very soon.

If you get the chance to try Mark-It again, I'd love to hear what you think!

Thanks,
Matt

**Comment by atomGit** [comment]
i bookmarked the AMO page and will certainly try it again as soon as i see the update 

thanks much!
